name: optaa
channels:
  - defaults
  - conda-forge
dependencies:
  - python 
  - pytest
  - jupyter
  # - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - requests
  - tqdm
  - yaml
  - python-dateutil
  - munch
  - h5py
  - h5netcdf
  - seaborn
  - cmocean