name: optaa
channels:
  - defaults
  - conda-forge
dependencies:
  - pytest
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - requests
  - tqdm
  - yaml
  - python
  - python-dateutil